# DSCI Project: Individual Planning Report

Library Required: tidyverse, repr

In [4]:
library(tidyverse)
library(repr)

## 1) Data Description

### players.csv

Overview: This dataset contains a list of players' personal information.

Number of Observations: 196

Number of Variables: 7

Variable Information:
| **Variable** | **Type** | **Description** |
|---------------|-----------|----------------|
| `experience` | Character | Player's skill level: one of *Beginner*, *Regular*, *Amateur*, *Pro*, or *Veteran*. |
| `subscribe` | Logical | Whether the player is subscribed to the newsletter. |
| `hashedEmail` | Character | The player's hashed email address. |
| `played_hours` | Numeric | Player's total playtime in hours. |
| `name` | Character | The player's name. |
| `gender` | Character | The player's gender. |
| `Age` | Numeric | The player's age in years. |

Collection Methods:
- `hashedEmail` and `played_hours` were likely collected from the game server's session log.
- The other variables were collected via surveys.

Potential Issues regarding variables
- `Age` has 2 missing values (code below)
- `gender` has many observations that are `Prefer not to say`, which is similar to missing values.

Potential Issues regarding the collection method
- The classification of a player's `experience` is ambiguous, as a player can be skilled in different areas of the game (e.g. pve, pvp)


Summary Statistics of numeric variables, `Age` and `played_hours` (Calculations in code cells below):
| Variable      | Mean      | Std       | Min | Max  |
|---------------|----------|----------|-----|------|
| played_hours  | 5.85 | 28.36 | 0   | 223.1|
| Age           | 21.14 | 7.39 | 9   | 58   |

In [5]:
#Load Data
players <- read_csv('data/players.csv')

#Detect Missing Values
players |>  summarise(across(everything(), ~ sum(is.na(.x))))

Rows: 196 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): experience, hashedEmail, name, gender
dbl (2): played_hours, Age
lgl (1): subscribe

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  experience subscribe hashedEmail played_hours name gender Age
1 0          0         0           0            0    0      2

In [6]:
# Calculate Mean
cat("=== Mean Summary ===\n")
players |>  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))


# Calculate Standard Deviation
cat("=== Standard Deviation Summary ===\n")
players |>  summarise(across(where(is.numeric), ~ sd(.x, na.rm = TRUE)))

# Find Minimum
cat("=== Minimum Summary ===\n")
players |> summarise(across(where(is.numeric), ~ min(.x, na.rm = TRUE)))

# Find Maximum
cat("=== Maximum Summary ===\n")
players |> summarise(across(where(is.numeric), ~ max(.x, na.rm = TRUE)))

=== Mean Summary ===

  played_hours Age
1 5.845918     21.13918

=== Standard Deviation Summary ===

  played_hours Age
1 28.35734     7.389687

=== Minimum Summary ===

  played_hours Age
1 0            9

=== Maximum Summary ===

  played_hours Age
1 223.1        58

### session.csv

Overview: This dataset contains a list of information on each recorded play session.

Number of Observations: 1535

Number of Variables: 5

Variable Information:
| **Variable** | **Type** | **Description** |
|---------------|-----------|----------------|
| `hashedEmail` | Character | The player's hashed email address. |
| `start_time` | Character | The start time of the play session |
| `end_time` | Character | The end time of the play session. |
| `original_start_time` | Numeric | UNIX timestamp of start time (milliseconds since epoch) |
| `original_end_time` | Numeric | UNIX timestamp of start time (milliseconds since epoch) |

Collection Methods:
- Data were likely collected via the game server's session log.

Potential Issues regarding variables
- `original_start_time` and `original_end_time` appear to represent UNIX timestamps, but this cannot be confirmed without further details regarding how this variable is used.
- Both `end_time` and `original_end_time` have 2 missing values (code below).
- Both `end_time` and `start_time` are character data types.  This is not ideal for time analysis in R.
- For some observations, `original_start_time` and `original_end_time` are identical due to rounding, resulting in sessions that appear to have a duration of zero hours..  This may make these 2 variables less useful for time analysis.

Potential Issues regarding the collection method
- Unsure if time data was collected in the same timezone


Summary Statistics of numeric variables, `original_start_time` and `original_end_time`:
- As the 2 variables represent time, summary statistics will not be meaningful

## 2) Questions

Broad Question 2: We would like to know which "kinds" of players are most likely to contribute a large amount of data so that we can target those players in our recruiting efforts.

My Question: Can a player's `Age` predict the player's `played_time` in `players.csv`?

How will the dataset help:
- `players.csv` contains information on participants' age and play time.
- We can create a regression model using `Age` as the explanatory variable to predict `played_time`, then calculate how good the model performed using metrics such as RMSPE, Pearson coefficient, accuracy, etc.
- Some observations for age are missing. Since these observations do not contain the explanatory variable, they will be omitted before the analysis.